# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RetoolGUI.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(558, 745)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(15, 0))
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 531, 220))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.radNorm = QtWidgets.QRadioButton(self.layoutWidget)
        self.radNorm.setChecked(True)
        self.radNorm.setObjectName("radNorm")
        self.gridLayout.addWidget(self.radNorm, 2, 3, 1, 1)
        self.vbox = QtWidgets.QLineEdit(self.layoutWidget)
        self.vbox.setStyleSheet("color: rgb(255, 0, 0)")
        self.vbox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.vbox.setReadOnly(True)
        self.vbox.setObjectName("vbox")
        self.gridLayout.addWidget(self.vbox, 7, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 3, 1, 1)
        self.radHover = QtWidgets.QRadioButton(self.layoutWidget)
        self.radHover.setObjectName("radHover")
        self.gridLayout.addWidget(self.radHover, 3, 3, 1, 1)
        self.acq_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.acq_btn.setObjectName("acq_btn")
        self.gridLayout.addWidget(self.acq_btn, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 1, 1, 1)
        self.calc_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.calc_btn.setObjectName("calc_btn")
        self.gridLayout.addWidget(self.calc_btn, 2, 0, 1, 1)
        self.flipwind_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.flipwind_btn.setObjectName("flipwind_btn")
        self.gridLayout.addWidget(self.flipwind_btn, 3, 0, 1, 1)
        self.anglebox = QtWidgets.QSpinBox(self.layoutWidget)
        self.anglebox.setWrapping(True)
        self.anglebox.setMaximum(359)
        self.anglebox.setSingleStep(1)
        self.anglebox.setProperty("value", 14)
        self.anglebox.setObjectName("anglebox")
        self.gridLayout.addWidget(self.anglebox, 5, 2, 1, 1)
        self.wbox = QtWidgets.QSpinBox(self.layoutWidget)
        self.wbox.setMinimum(-1000)
        self.wbox.setMaximum(1000)
        self.wbox.setObjectName("wbox")
        self.gridLayout.addWidget(self.wbox, 1, 2, 1, 1)
        self.windbox = QtWidgets.QSpinBox(self.layoutWidget)
        self.windbox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.windbox.setWrapping(True)
        self.windbox.setAccelerated(False)
        self.windbox.setMinimum(-30)
        self.windbox.setMaximum(30)
        self.windbox.setObjectName("windbox")
        self.gridLayout.addWidget(self.windbox, 3, 2, 1, 1)
        self.radBoom = QtWidgets.QRadioButton(self.layoutWidget)
        self.radBoom.setObjectName("radBoom")
        self.gridLayout.addWidget(self.radBoom, 9, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 1, 1, 1)
        self.hbox = QtWidgets.QSpinBox(self.layoutWidget)
        self.hbox.setMinimum(-1000)
        self.hbox.setMaximum(1000)
        self.hbox.setObjectName("hbox")
        self.gridLayout.addWidget(self.hbox, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.radBigHover = QtWidgets.QRadioButton(self.layoutWidget)
        self.radBigHover.setObjectName("radBigHover")
        self.gridLayout.addWidget(self.radBigHover, 5, 3, 1, 1)
        self.radDig = QtWidgets.QRadioButton(self.layoutWidget)
        self.radDig.setObjectName("radDig")
        self.gridLayout.addWidget(self.radDig, 7, 3, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setStyleSheet("color:rgb(85, 87, 83)")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 9, 0, 1, 2)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 240, 521, 481))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 519, 479))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.calcTable = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.calcTable.setGeometry(QtCore.QRect(0, 0, 521, 481))
        self.calcTable.setObjectName("calcTable")
        self.calcTable.setColumnCount(3)
        self.calcTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.calcTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.calcTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.calcTable.setHorizontalHeaderItem(2, item)
        self.calcTable.horizontalHeader().setStretchLastSection(True)
        self.calcTable.verticalHeader().setVisible(False)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Aim Assistant v2"))
        self.radNorm.setText(_translate("MainWindow", "&Normal"))
        self.vbox.setPlaceholderText(_translate("MainWindow", "Power"))
        self.label_4.setText(_translate("MainWindow", "Shot Type:"))
        self.radHover.setText(_translate("MainWindow", "&Hover (Post hang only)"))
        self.acq_btn.setText(_translate("MainWindow", "&ACK"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>Barrel:</p></body></html>"))
        self.calc_btn.setText(_translate("MainWindow", "&Calc"))
        self.flipwind_btn.setText(_translate("MainWindow", "&Invert Wind"))
        self.radBoom.setText(_translate("MainWindow", "&Boomerang"))
        self.label_2.setText(_translate("MainWindow", "Wind:"))
        self.label_5.setText(_translate("MainWindow", "Height:"))
        self.label.setText(_translate("MainWindow", "Width:"))
        self.radBigHover.setText(_translate("MainWindow", "&Big Hover"))
        self.radDig.setText(_translate("MainWindow", "&Tunneler"))
        self.lineEdit.setText(_translate("MainWindow", "07 28 90 24 00 14 10 00 00"))
        self.calcTable.setSortingEnabled(True)
        item = self.calcTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Power"))
        item = self.calcTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Angle"))
        item = self.calcTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Error"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

